server:
  port: 8080

spring:
  application:
    name: statusmonitor
  datasource:
    url: jdbc:postgresql://localhost/statusmonitordb
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always
      #schema-locations: classpath:/schema.sql
      data-locations: classpath:/data.sql      # default location,classpath, src/main/resources

#    TRACE: The lowest level of logging that provides the most detailed information about what is happening in the application.
#    DEBUG: A level higher than TRACE that provides information about application flow and internal state.
#    INFO: A level higher than DEBUG that provides information about what the application is doing and its status.
#    WARN: A level higher than INFO that indicates potentially harmful situations.
#    ERROR: The highest level of logging that indicates errors that may cause the application to malfunction or fail.

logging:
  level:
    #root: ERROR
    root: INFO
    org.springframework.security: DEBUG

---

spring.config.activate.on-profile: docker

server.port: 80

spring:
  datasource:
    url: jdbc:postgresql://statusmonitor-db:5432/statusmonitor